name: Automatic Tech Upgrade

on:
    workflow_dispatch

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Install Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 12

            - name: Log Package Version Status
              run: npm outdated

            - name: Install Packages
              run: yarn install

            - name: Update Dependencies
              run: yarn deps:update

            - name: Install Updated Packages
              run: yarn install

            - name: Sanity Testing
              run: yarn test:sanity

            - name: Commit and Push
              uses: EndBug/add-and-commit@v5
              with:
                  branch: master
                  author_name: attilagyongyosi
                  author_email: attilagyongyosi0@gmail.com
                  message: 'ci: automatic package update commit'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
