name: CI

on: push

jobs:
    build:
        strategy:
            matrix:
                node: [ 12 ]
                os: [ ubuntu-latest, windows-latest, macos-latest ]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Install Dependencies, Run tests & build
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}
            - run: yarn install
            - run: yarn test
            - run: yarn bundle
