name: Release new version

on:
    workflow_dispatch:
        inputs:
            type:
                description: 'Semver component to bump and release'
                required: true
                default: 'minor'

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
            - name: Install Dependencies
              uses: actions/setup-node@v1
              with:
                  node-version: 12
            - run: yarn install
            - name: Release new version
              run: yarn release ${{ github.event.inputs.type }}
